>P1;template_0
structure:template_0.pdb:.:.:.:.::::
PRWEQT-------HLTYRIENYTPDLPRADVDHAIEKAFQLWSNVT-PLTFTKVSE----
---GQADIMISFVRGDHRDNSPFDGPG--------GNLAHAFQPGPG--IGGDAHFDEDE
--------RWTNNFREYNLHRVAAHELGHSLGLSHSTDI--GALMYPSYTF--SGDVQLA
QDDIDGIQAIYGR-S*

>P1;template_1
structure:template_1.pdb:.:.:.:.::::
GQKWQHK------HITYSIKNVTPKVGDPETRKAIRRAFDVWQNVT-PLTFEEVPYSELE
NGKRDVDITIIFASGFHGDSSPFDGEGGFLAHAYFP----------GPGIGGDTHFDSDE
PWTLGNPNH-----DGNDLFLVAVHELGHALGLEHSNDP--TAIMAPFYQYMETDNFKLP
NDDLQGIQKIYGP--*

>P1;model_1_mt
sequence:model_1_mt:.:.:.:.::::
-------------TVTVTYDPSNA----PSFQQEIANAAQIWNSSVRNVQLRAG------
---GNADFSYYEGNDS---RGSYAQTD--------G----------H--GRGYIFLDYQQ
--------N-----QQYDSTRVTAHETGHVLGLPDHYQGPCSELMSGGGPGPSCTNPYPN
AQERSRVNALWANG-*
