>P1;template_0
structure:template_0.pdb:.:.:.:.::::
PRWEQT-------HLTYRIENYTPDLPRADVDHAIEKAFQLWSNVT-PLTFTKVSE----
---GQADIMISFVRGDHRDNSPFDGPG--------GNLAHAFQPGPG--IGGDAHFDEDE
--------RWTNNFREYNLHRVAAHELGHSLGLSHSTDI--GALMYPSYTF--SGDVQLA
QDDIDGIQAIYGR-S*

>P1;model_1_st
sequence:model_1_st:.:.:.:.::::
-------------TVTVTYDPSNA----PSFQQEIANAAQIWNSSVRNVQLRAG------
---GNADFSYYEGNDS---RGSYAQTD--------G----------H--GRGYIFLDYQQ
--------N-----QQYDSTRVTAHETGHVLGLPDHYQGPCSELMSGGGPGPSCTNPYPN
AQERSRVNALWANG-*
